### ISSUE TITLE
A public collateral and tx broadcast service

### ISSUE THREAD

**Issue by yihuang** [cardano-foundation/CIPs#167]
## Context

To spend plutus script output,  we need to provide collateral, which is burned if script execution failed.
This have several implications:
- Wallet need to reserve a UTxO to use as collateral, usually several ADAs, not much, but still something, and maybe confusing to user.
- If wallet didn't do full validation on tx, there's risk that one might lose the collateral.

## Solution

It seems to me that we can have some public services to provide the collateral:
- Wallet query collateral UTxO from the service `/get_collateral`
- Wallet use them to build and witnesses the tx.
- Wallet send the tx to the service `/broadcast_tx`
  - The service will validate the tx.
  - Witness the collateral.
  - Broadcast.

## Security
- User don't need to trust the service provider, since the tx is not malleable.
- The collateral is not at risk of burn, since service provider will validate the tx themselves.

**Comment by rphair** [comment]
@yihuang there needs to be a lot more detail before this proposal could be considered a complete draft, although there's a lot of related discussion here: https://github.com/cardano-foundation/CIPs/pull/104

**Comment by yihuang** [comment]
yeah, and I think the up coming collateral output will make the process convenient enough. closing now.
