### ISSUE TITLE
CIP-0025 <asset_name> encoding

### ISSUE THREAD

**Issue by mkazlauskas** [cardano-foundation/CIPs#191]
It is not clear what encoding should `<asset_name>` be. I originally assumed it to be hex, but it seems that people are using utf8. It would be great to specify it explicitly in the CIP. @alessandrokonrad

**Comment by alessandrokonrad** [comment]
Yeah that was a mistake, the default encoding here is `utf8` now, since pretty much everyone is using it.
`hex` would definitely better and I would suggest having that in a version 2 of the NFT metadata standard. So we can keep backwards compatibility for the current format.

**Comment by KtorZ** [comment]
Addressed in https://github.com/cardano-foundation/CIPs/pull/193
