### ISSUE TITLE
CIP-0001: support parameter updates and CIP editor changes

### ISSUE THREAD

**Issue by mark-stopka** [cardano-foundation/CIPs#201]
As discussed on today's meeting, [CIP-0001](https://developers.cardano.org/docs/governance/cardano-improvement-proposals/CIP-0001) no longer fits the community needs; following processes should be added:

- [ ] Parameter update track
- [ ] On-boarding of new CIP editors
- [ ] Off-boarding of existing CIP editors

If you think some other processes should be added, please let me know and I'll add it in the ticket body. Regarding the magnitude of changes, I believe new CIP should be created for these processes, question is should we make a complete replacement, or just create a new CIP and link the extension to the [CIP-0001](https://developers.cardano.org/docs/governance/cardano-improvement-proposals/CIP-0001)?

CC: @SebastienGllmt, @KtorZ, @crptmppt?

**Comment by rphair** [comment]
@mark-stopka we're ready to merge the latest CIP-0001 draft revisions with https://github.com/cardano-foundation/CIPs/pull/366... I believe this satisfies all your requirements above; what do you think? (cc @KtorZ)

**Comment by mark-stopka** [comment]
> @mark-stopka we're ready to merge the latest CIP-0001 draft revisions with #366... I believe this satisfies all your requirements above; what do you think? (cc @KtorZ)

I agree... closing in favor of https://github.com/cardano-foundation/CIPs/pull/366
