### ISSUE TITLE
Proposal for adding an index to improve navigation within this repo

### ISSUE THREAD

**Issue by v-almonacid** [cardano-foundation/CIPs#36]
Right now, if you come to this repo looking for information on some topic, but you don't know which CIP covers it, you basically need to check every CIP folder. As the number of submissions increases, this becomes less and less practical.

It'd be nice if we can just have an index in the README, something like:

- [CIP-1 - CIP Process](https://github.com/cardano-foundation/CIPs/blob/master/CIP1/CIP1.md)
- [CIP-2 - Coin Selection Algorithms](https://github.com/cardano-foundation/CIPs/blob/master/CIP2/CIP2.md)
- ...

...perhaps with different sections for each status.

Maybe the idea was to have https://cips.cardano.org for this? If that's the case, that website is not playing that role and is not up-to-date.

**Comment by matiwinnetou** [comment]
+1

Maybe you could create a PR to repo with such a thing, if not I will do this...

**Comment by v-almonacid** [comment]
Closing since it's been taken care of.

**Comment by crptmppt** [comment]
@v-almonacid I still think it can be improved - cips.cardano.org is meant for non coders and auto builds from this repo. but is still not intuitive to navigate. It's being improved, little by llittle.   
Current reorg has normalized CIP folder names, we could append CIP title next to the numbers? Else the new readme now has a table (which used to be in the notes themselves before) that serves that purpose. Issue with moving structure is that github might not make it clear which file came from where
