### ISSUE TITLE
CIP-9 Updatable params require a hard-fork event? Should be soft-fork.

### ISSUE THREAD

**Issue by ccgarant** [cardano-foundation/CIPs#369]
In CIP-9, Updatable Protocol Parameters, it states:
> "A change to the major protocol parameter version triggers a "hard fork" event. This will require stake pool operators to upgrade to a new software version that complies with the new chain production protocol as well as being able to verify the construction of the chain."

Upon investigation, a hard-fork is 5 of 7 genesis signing keys, required for major changes like Non-Updatable Parameters.

However, the Updatable Params only require 4 of 7 signing keys, and is a "soft-fork" (backwards compatible with old nodes), and much easier.  Requesting permission to make updates to reflect this.  This came up in a stake rewards equation minPoolCost discussion.

Ref Duncan Coutts clarification [here](https://github.com/input-output-hk/ouroboros-network/issues/4051#issuecomment-1293283856)

**Comment by KtorZ** [comment]
Hey, that's not quite how it works. In the discussion thread, I believe Duncan really meant '5' and not '4', as the current quorum parameter is set to 5.

What Duncan explains in this comment is that a hard-fork ships with a code change, so a super majority of nodes must have adopted the code change before the genesis delegates pull the trigger and submit/vote a proposal. This is effectively done by submitting an protocol parameter update that increase the protocol major version. 

In a comparison, a soft fork is merely updating an existing parameter, within the existing semantic known to all nodes. So there's no particular need for synchronization. Every node will keep working the same after the parameter update, there's no need to ship a code update.

**Comment by ccgarant** [comment]
Thanks for reviewing @KtorZ. 

I guess from reading the CIP, it's not abundantly clear what exactly are the benefits of the updatable vs non-updatable parameters. I feel like there should be more explicit ultra-clear delineation between the two. Currently they seem to be exactly the same from the text. 

Also, there seems to be misinformation around the updatable param updates requiring 4 signatures. I am among them 😅. 

A clarification update and public info sharing would probably go a long way for us Normies.

**Comment by ch1bo** [comment]
I just realized that CIP-9 is a bit out-of-date as well. At least it does not include updates of Alonzo and Babbage?

**Comment by KtorZ** [comment]
They are in different CIPs @ch1bo: 

- Alonzo -> [CIP-0028](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0028)
- Babbage -> [CIP-0055](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0055)

With the CIP-0001's rework, we are also planning some better categorization of the CIPs which should help to find those. We could also have them reference one another to ease navigation.

**Comment by rphair** [comment]
@ccgarant with the answers to the questions above, and the merged https://github.com/cardano-foundation/CIPs/pull/370 linking the proposals together as in https://github.com/cardano-foundation/CIPs/issues/369#issuecomment-1307290514, would you be satisfied if we close this one?
