### ISSUE TITLE
Update older CIPs for revised CIP-0001

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/CIPs#389]
The CIP-0001's rework has been merged. In this rework, we've changed the preamble header structure and renamed some of the sections. Thus, for the sake of consistency, we'll need to update past CIPs to reflect this new structure. This issue is meant to help organizing the work around that.  For each CIP, we need to:

- Convert `Authors` to an actual bullet-point list (one name per line, starting with `-`)
- Remove any field that is no-longer supported (e.g. `type`)
- Add a `Discussions` field with a list (same as authors) of links to past discussions. At the very least, this should contain a link to the original PR (`git log` comes in handy to figure this out).
- Add any other new fields specified by CIP-0001 (`Category`, `Implementors`...).
- Some sections have been renamed and need to follow the structure given by the new CIP template. In particular, the _path to active_ needs to divided into two sub-sections. It may very much be the case for older CIPs that the _path to active_ is incomplete; which should be reflected in the new structure (CIPs without implementors or implementation plan shall be explicitly labelled as such).
- Update the top level `README.md` if there is a status change for this CIP in the table.

> **Warning** We may introduce categories as we see fit; however, categories that would refer to specific areas of the ecosystem (e.g. `Ledger` which also applies to RSS proposals) need to be endorsed by the respective teams of maintainers. Until this happens, we should refrain from using these categories and simply use `N/A` in the meantime.

In terms of process; here below is a list of all (currently) merged CIPs; Each item can be converted into issue and assigned to one person. Thus, if you intend to help, make an issue out of one of the point, assign it to you and make a follow-up PR with the changes. Once all CIPs have been updated, we should be able to repair the website build.

- [x] #720
- [x] #390
- [x] #397
- [x] #400
- [x] #451
- [x] #644
- [x] #532
- [x] #646
- [x] #649
- [x] #651
- [x] #653
- [x] #655
- [x] #402
- [x] #657
- [x] #603
- [x] #659
- [x] #661
- [x] #642
- [x] #663
- [x] #410
- [x] #665
- [x] #667
- [x] #533
- [x] #534
- [x] #669
- [x] #671
- [x] #673
- [x] #675
- [x] #677
- [x] #681
- [x] #682
- [x] #684
- [x] #686
- [x] #689
- [x] #691
- [x] #604
- [x] #693
- [x] #695
- [x] #697
- [x] #699
- [x] #701
- [x] #704
- [x] #706
- [x] #708
- [x] #710
- [x] #712
- [x] #714
- [x] #716
- [x] #535
- [x] #718
- [x] #722
- [x] #724
- [x] #726
- [x] #728
- [x] #721

**Comment by rphair** [comment]
@KtorZ before we get too far into this list, can we reformat the items in the outline above from e.g. :
> Adjust preamble and structure of CIP-0003 to abide by new CIP-0001

to
> CIP-0003 | Adjust preamble and structure to abide by new CIP-0001

Otherwise the email notifications for all these new PRs and issues will be hard to tell apart, with the distinguishing element so deep into the title.  They'll still collate as currently above but will require a wider screen to view.  There could also be some historical benefit to using the same format that we use for all our other issues & PRs... rather than having them all stand out as parts of a once-off editing process.

If you and @crptmppt @SebastienGllmt agree I can easily script that change... as could you, but I'm ready, willing & motivated to do it right now 😎

**Comment by KtorZ** [comment]
Done!

**Comment by rphair** [comment]
@Ryun1 @KtorZ with the new versioning clarification proposed in https://github.com/cardano-foundation/CIPs/pull/563 I think we might also have to add version treatment to the outline of things to do here... if possible (this could depend on communication with authors & other proponents, which might not be possible).

**Comment by rphair** [comment]
@KtorZ @Ryun1 @Crypto2099 my Catalyst Fund 10 project has been approved, with filing PRs for all of these as the Q4 2023 milestone. 😬 I've added it to the CIP meeting agenda today so we can talk about how the editorial process would best proceed for these. 😇

**Comment by rphair** [comment]
FYI as of now, I've created issues for all the CIP remediations above & linked each one of the unresolved issues to one of 41 new PRs which we can work on refining, approving & merging some time soon in the New Year. 🎉

**Comment by Ryun1** [comment]
Great work on this @rphair 💪

Im sure it will feel very satisfying to press the `close issue button` 🤠

**Comment by rphair** [comment]
Thanks for the great backup & insight... you guys are awesome 🤩
