### ISSUE TITLE
CIP-0020 | Adjust preamble and structure w.r.t CIP-0001

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/CIPs#410]
Partially done in #394. Only the `Path to Active` is missing from there as well as renaming the "Motivation" and "Rationale" to their question-like format. But preamble and other sections have been updated accordingly.

**Comment by rphair** [comment]
OK, when I was re-reading this I was wondering how in general to assign `Path to Active` for proposals already `Active` for a while... will be following this one 🤓

**Comment by rphair** [comment]
thanks @KtorZ & I'll infer what might already have been stated or obvious, but is counter-intuitive for me... that _all_ merged proposals (unless maybe deliberately declared `Inactive`?) must have a `Path to Active` that describes _both_ the acceptance criteria (even if already accepted) & the implementation plan (even if already implemented).

**Comment by rphair** [comment]
Fixed by #647.
