### ISSUE TITLE
CIP-35 and the Draft status

### ISSUE THREAD

**Issue by JaredCorduan** [cardano-foundation/CIPs#420]
The `Draft` status of CIPs has been removed. The Plutus category of CIPs, however, still makes use of the distinction between `Draft` and `Proposed` (see CIP-35).

**Comment by rphair** [comment]
@KtorZ - @JaredCorduan is right!  [Additions to the Plutus Core Builtins](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0035#additions-to-the-plutus-core-builtins) requires progression through 3 stages: if not {`Draft`, `Proposed`, `Active`} then something else would need to replace `Draft` if they weren't allowed to use that term.

So I would think the solution would be updating `CIP-0001` to indicate that the `Draft` status is _only acceptable for the `Plutus` category_... which removes the inconsistency as far as I can tell.

cc @michaelpj @SebastienGllmt @crptmppt

**Comment by michaelpj** [comment]
CIP-35 needs some work to make it match the new setup better. I think probably I'll just merge the Draft and Proposed criteria.

**Comment by rphair** [comment]
As far as I can tell this is fixed by https://github.com/cardano-foundation/CIPs/pull/428 (thanks @michaelpj); any last words @JaredCorduan before closing?

**Comment by JaredCorduan** [comment]
looks great, thanks all!
