### ISSUE TITLE
Website is not updating

### ISSUE THREAD

**Issue by michaelpj** [cardano-foundation/CIPs#436]
The website doesn't seem to have updated recently, e.g. the new CIP-001 is not present there.

**Comment by rphair** [comment]
thanks @michaelpj - we've just been talking about that.  @KtorZ is more intimately connected with this but publicly we're facing a huge update in #389 before replacing the _ad hoc_ scripts that built [cips.cardano.org](https://cips.cardano.org) with something robust & maintainable that will reflect the new preamble & outline structure.

I missed it the first few times I read the OP for that issue myself, but it clearly indicates that this overhaul of CIPs themselves is a prerequisite for getting those that web site working again.  If we can't get the manpower to do it between CIP editors & CF itself then I might submit a proposal in Fund10 for one or both of those things.

**Comment by michaelpj** [comment]
I'm a little confused. Would it be hard to support the union of the old and new metadata in the site builder while things transition? Blocking the website on updating all the old CIPs seems like a mistake to me. At the moment people can't even see the new CIP-001 without looking in the source!

**Comment by KtorZ** [comment]
> I'm a little confused. Would it be hard to support the union of the old and new metadata in the site builder while things transition? 

No it wouldn't. There's simple no one who's bothered doing it. I was hoping that tackling #389 would be faster but it's bit dragging for a while now.

**Comment by KtorZ** [comment]
I'll bother. Give me few minutes.
