### ISSUE TITLE
CIP links to hydra.iohk.io are all broken

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/CIPs#485]
Reposted with more detail from https://github.com/cardano-foundation/developer-portal/issues/988.

At the current time there is no link from any merged CIP to any URL at `hydra.iohk.io` which works.  Currently this is (from `grep hydra.iohk.io */README.md`:

---

CIP-0006 line 19: ([delegation-design-specification Section 4.2)](https://hydra.iohk.io/build/790053/download/1/delegation_design_spec.pdf)
CIP-0025 line 27: (Section 4.1 in the paper: https://hydra.iohk.io/build/5400786/download/1/eutxoma.pdf)
CIP-0059 line 37: [specification](https://hydra.iohk.io/job/Cardano/cardano-ledger/specs.shelley-ma/latest/download-by-type/doc-pdf/shelley-ma).
CIP-0059 line 83: [Shelley ledger specification](https://hydra.iohk.io/job/Cardano/cardano-ledger/shelleyLedgerSpec/latest/download-by-type/doc-pdf/ledger-spec)).
CIP-0074 line 59: https://hydra.iohk.io/build/790053/download/1/delegation_design_spec.pdf
CIP-1854 line 231: A Formal Specification of the Cardano Ledger | https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/shelleyLedgerSpec/latest/download-by-type/doc-pdf/ledger-spec
CIP-1854 line 244: [ledger-spec.pdf]: https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/shelleyLedgerSpec/latest/download-by-type/doc-pdf/ledger-spec
CIP-1855 line 102: A Formal Specification of the Cardano Ledger | https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/shelleyLedgerSpec/latest/download-by-type/doc-pdf/ledger-spec
CIP-1855 line 112: [ledger-spec.pdf]: https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/shelleyLedgerSpec/latest/download-by-type/doc-pdf/ledger-spec

---

@KtorZ @Ryun1 how can we officially request updates for these links to canonical documents (including any declarations of document being obsolete)?  If someone can track down that information I'll submit the PR to edit the affected CIPs.

**Comment by Ryun1** [comment]
@rphair 

Most of these are links to the Ledger spec, so Im not sure why `hydra.iohk.io` was being used.

Regardless, see [this commit](https://github.com/input-output-hk/cardano-ledger/commit/7bb099326546f910539b75e835b07322fdf88bc5) to Ledger repo, seems to be fixing `hydra.iohk.io` locations with ones from Github releases - maybe we can use a similar approach?
