### ISSUE TITLE
CIP-0068 | question on reference code

### ISSUE THREAD

**Issue by jerrybassat7** [cardano-foundation/CIPs#498]
https://github.com/cardano-foundation/CIPs/blob/5bcdb9b679f35a28801adedfd7114090c6bc5472/CIP-0068/ref_impl/offchain.ts#L66

Looking at the reference Code provided for CIP-68, Im not sure i understand this line and what is used for, it could be clarified.

**Comment by rphair** [comment]
@alessandrokonrad would you care to field this one? 🙏

**Comment by alessandrokonrad** [comment]
@jerrybassat7 this line has nothing to do directly with CIP-68. The example minting policy requires to spend a certain UTxO to create a unique NFT.
