### ISSUE TITLE
Versioning alternatives

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/CIPs#520]
So far the CIP editors have not been willing to impose a universal versioning requirement on CIPs mainly because of different treatments of "versioning" according to each application and CIP subject.  We've only rejected the idea that a CIP `Version:` field should be added to the header (suggesting it should be described in the CIP text itself), and have left all definitions and applications of versioning to each CIPs author or maintainer.

Given this _laissez-faire_ approach we have somehow missed the particular importance of versioning for CIP-0068.  My own understanding (forgive me, I'm not a developer in this area) was:
- new asset name labels being added via CIP-0067 would define the set of labels being supported, so the recent addition of the `444` asset name label wouldn't cause any incompatibilities that a version "bump" would fix.
- there is a `version` defined in the `datum` part of the schema which appears to be set always to `1` which (I guess) shows that these datums all together establish a "version 1" of CIP-0068 as it exists now, even with the recent addition.

In the discussion for https://github.com/cardano-foundation/CIPs/pull/494 I didn't see any calls by either @AndrewWestberg, @alessandrokonrad, or implemetor @mmahut to add an explicit versioning scheme, although it's come up after the fact that this would have been a good idea.  (If that were explicitly suggested somewhere then please somebody link to it below.)

Whatever may have been missing in the CIP review & editing process is bracketed in the Discord discussion between [here](https://discord.com/channels/971785110770831360/992011119872970762/1108336998634246185) and [here](https://discord.com/channels/971785110770831360/992011119872970762/1113362054917660735).  There were some longer, prior discussions on Discord about versioning which I would really like to ensure at this point have not been interpreted as an indication that CIP editors are against versioning in general.

So this issue is to get input from all concerned parties to:
- (ASAP) decide the best way to update CIP-0068 to give @mmahut and other implementors a solid base for to support this standard;
- (maybe) decide on a versioning scheme for applicable CIPs, with semantic versioning being generally recommended (most recently by @KtorZ - cc @matiwinnetou);
- more fully consider, between authors and editors, whether this kind of support issue could be avoided in the future by enabling a `Version:` field in CIP headers;
- decide whether CIP versioning should be mandatory in any particular, well-defined cases... e.g. for CIPs which present anything like an "API" as e.g. CIP-0068 presents to Blockfrost;
- (finally) list whatever precise rules can be used to update CIP-0001 accordingly.

Since I've been the main responder to the latest general questions about CIP versioning, I will keep trying to bring in prior discussions on the matter and will keep referring authors & reviewers here to get as broad a consensus as possible.

Please also tag any concerned parties and feel free to re-post any prior discussions or perceived omissions here, to be sure we make a full inventory of everyone's opinions and requirements.

**Comment by AndrewWestberg** [comment]
Since some people have already implemented parsing for CIP-68, I would recommend that we bump the version to 2 for the version that also supports the 444 prefix.

For most of these CIP standards, I would think semver is probably overkill. You'd have to store it in a list with major,minor,point integers.  Having a single integer version is simpler and already specified in both CIP-68 and CIP-25, etc...

**Comment by Ryun1** [comment]
Thanks for the great write up here @rphair, I think versioning is clearly an important topic for the community and probably warrants a large discussion. I am happy to help work on a CIP-0001 PR and or a CPS for the versioning of CIPs.

**Comment by rphair** [comment]
Good to know @Ryun1 and I hope we are setting a precedent to be proactive and well-documented in each CIP about either an implementation of versioning or an explanation of why versioning won't be used... as in your latest https://github.com/cardano-foundation/CIPs/pull/509#issuecomment-1578359112

**Comment by rphair** [comment]
@mmahut I brought up this issue at the CIP editors' meeting today and we agreed the top priority is to create a PR to update CIP-0068 with a new version accommodating the `444` RFT Standard introduced in https://github.com/cardano-foundation/CIPs/pull/494.

In conversation with @KtorZ I volunteered to do the PR, but upon further research I don't think it's a simple matter of increasing a version number.  How the version number is applied seems to involve some design decisions, as per these questions:

1 - Would the `version` number (an integer "serial number" making more sense than a semantic version) be increased from 1 to 2 for
- _all_ the defined asset name labels (indicating that the `444` designation is now an alternatives for this metadatum); or
- _only_ the `444` asset name label (leaving the previously defined asset name labels unchanged)?

It seems also then the document itself should have a version number equal to the highest defined `version` number, and therefore also a version history (table) indicating which CIP-0068 version corresponds to what list of supported asset name labels.

The choice here would indicate a paragraph to add to the specification, saying whether a new asset name label increments _all_ the asset name label version numbers or just the one(s) that were added in the new version.

2 - If there is to be a (minimum) version number for each of these asset name labels (i.e. the second choice above), that suggests to me the best place to define a "minimum supported version" would be **in the [reference.json](https://github.com/rphair/CIPs/blob/master/CIP-0067/registry.json) table of CIP-0067** rather than the text of CIP-0068, since presumably services like Blockfrost will need to make use of this table.

Therefore @mmahut please I think it is time for you to step in and let us know exactly what version definition would satisfy the problem you pointed out [here](https://discord.com/channels/971785110770831360/992011119872970762/1108336998634246185):

> Should the CIPs be in some way versioned? At Blockfrost, we claim to suppor CIP-68 but a totally new implementation has been added to it, making it incompatible for now.

because it will be too much trial & error for me to propose a versioning scheme for a system that I have no practical experience with... though if @KtorZ understands the requirement well enough then maybe I could do the updates based on his recommendations. (cc @AndrewWestberg)

**Comment by KtorZ** [comment]
I'll propose something @rphair, and continue the discussion from there. I am leaning towards an overarching version number that applies to the entire specification. As well as disclaimers associated with newly introduced or removed elements from new versions.

**Comment by rphair** [comment]
Recent comment about applying a version to the overall spec (i.e. the CIP document) as opposed to components of it (or no version at all): https://github.com/cardano-foundation/CIPs/pull/509#issuecomment-1581020372

> ... we regretted that CIP-30 did not have a version number for its spec to manage this change

**Comment by rphair** [comment]
I believe the `CIP-0068` issue has been fixed by https://github.com/cardano-foundation/CIPs/pull/523, with the decision to version each of the asset name labels with respect to an overall version number.  I didn't think of this before but an additional advantage of the way this is written is that it allows labels support to be dropped in future versions (e.g. if a label was split).

Especially if there were lots more labels someday, we should still keep in mind the future option of defining the supported versions (`min_version` and `max_version`) in the `CIP-0067` table.

Please let's keep discussion on this issue going until we have the same kinds of matters resolved for some other CIPs. 🤓

**Comment by rphair** [comment]
@Crypto2099 now that there is a tangible PR for versioning requirements I think we will have to continue the discussion here: https://github.com/cardano-foundation/CIPs/pull/563 ... I'll keep your last https://github.com/cardano-foundation/CIPs/issues/520#issuecomment-1640317017 in mind to see if there's any way these two goals are compatible (it may help for you to restate your comment there in terms of the proposed changes).

**Comment by rphair** [comment]
@Crypto2099 @AndrewWestberg in hindsight I should not have closed this since your last suggestion https://github.com/cardano-foundation/CIPs/issues/520#issuecomment-1640317017 is well outside the scope of https://github.com/cardano-foundation/CIPs/pull/563 or any changes to CIP-0001 that are likely to be universally agreed upon any time soon.

Therefore we should keep this open in the long term to accumulate & debate such suggestions.  After the CIP-0068 matter was resolved early on with https://github.com/cardano-foundation/CIPs/pull/523, the "thin" dev feedback we've had in this issue so far might simply have been because of the no-longer-appropriate title.  So I'll give it a more meaningful one & hopefully that will attract more attention to your last suggestion & any other alternatives.

**Comment by rphair** [comment]
This actually closed automatically (and I'm not really sure why GitHub did it) but I don't personally see a need to keep it open anymore, since the new versioning standards seem pretty well adopted by the whole community now.  cc @Ryun1

**Comment by Ryun1** [comment]
We can always reopen, or open a new one when/if the problem arises again 😎
