### ISSUE TITLE
zipmortesson750116@gmail.com@Hornan7 the document content looks great in readability and formatting: thanks to yourself and whoever you are working with to achieve this, with ongoing thanks for offering to keep it updated.

### ISSUE THREAD

**Issue by Celiaparra** [cardano-foundation/CIPs#544]
@Hornan7 the document content looks great in readability and formatting: thanks to yourself and whoever you are working with to achieve this, with ongoing thanks for offering to keep it updated.

To my knowledge we've not had a parallel language version of a CIP before, so here are my suggestions which @KtorZ @Ryun1 might confirm or debate:

1 - The CIP header data at the beginning of the document, for all translations other than the primary (English) language, should be human- rather than machine-readable.  We are still catching up on our tooling to build generated web sites ([cips.cardano.org](https://cips.cardano.org/) and [developers.cardano.org/docs/governance/cardano-improvement-proposals](https://developers.cardano.org/docs/governance/cardano-improvement-proposals)) which can only happen after we finish standardising header data in a single language (https://github.com/cardano-foundation/CIPs/issues/389)... perhaps someday we will have language independence in the CIP database but we're far from ready to support that.

Therefore any usage of the machine-readable format in the header for multiple languages is going to be ignored, and it doesn't format properly on GitHub for the human reader: so I would recommend these fields be put in Markdown prose (e.g. lists of authors and discussion links) at the beginning of the document: for your convenience and that of your readers.

2 - Your impressive commitment to "keeping it updated" needs to be documented somehow, both before this PR is merged and into the future:

2a) _at least_: the translator name(s), human readable date, and GitHub hash of the English/primary CIP-1694 document which you have translated in your non-English version, or:

2b) _preferably, in my opinion_: a "version history" table which has this information added as a new line of a table or list each time a new translation is submitted as a PR.

At it stands now, there is no notion of "we" other than you, and no notion of "original document" except presumably the latest commit in CIP-1694 listed here (https://github.com/cardano-foundation/CIPs/commits/master/CIP-1694/README.md)... currently only one commit, but that is about to change radically in light of https://github.com/cardano-foundation/CIPs/pull/380#issuecomment-1614916372.

But your brilliant work is just a couple steps away of achieving multi-lingual auditability for this document and I assure you I/we will do everything we can to assist you in that effort. 🤓

_Originally posted by @rphair in https://github.com/cardano-foundation/CIPs/pull/539#pullrequestreview-1511148368_

**Comment by KtorZ** [comment]
Not sure if this is spam or someone genuinely not understanding how to use Github. Either way, closing this issue as it is not relevant (mostly copy-pasting comments from another PR).
