### ISSUE TITLE
CIP-1694: Default DRep

### ISSUE THREAD

**Issue by paradoxicalsphere** [cardano-foundation/CIPs#558]
I would like to suggest making the ```Abstain``` DRep a default setting for all existing and new wallets so that the ADA user experience--particularly for new users in the Cardano ecosystem--is not complicated further by adding another layer of delegation in order to access our funds.

Setting a default DRep also improves meeting the requirement of high adoption for CIP-1694.

I author an important idea designed to be complementary to CIP-1694 https://github.com/paradoxicalsphere/cardano-improvement-proposals/blob/main/CIP-x/README.md

**Comment by Ryun1** [comment]
I like the idea of an "default" @paradoxicalsphere, but this is down to how wallets to handle this. Wallets integrating a "default" DRep delegation at time of stake pool delegation could be a reasonable approach, but we could not really stipulate it in a CIP.
