### ISSUE TITLE
CIP-1694: A need to add the option `Abstain` as a state for each Constitutional Committee members.

### ISSUE THREAD

**Issue by Hornan7** [cardano-foundation/CIPs#566]
I believe it would be important to add `Abstain` as a state option for each Constitutional Committee member who for some reason cannot perform their duties temporarily (serious illness, vacation, death in the family etc) but who is nevertheless appreciated by his peers and the community. This (as a state option) would allow them to automatically vote abstain on all governance actions and, therefore, not be taken into account in the `threshold` of the Constitutional Committee until he/she resumes his/her functions without having to oust him from the Committee. This would also prevent him/her from having to vote `Abstain` on all governance actions during his/her recovery.

**Comment by Ryun1** [comment]
For me this raises more questions, which are likely harder to answer than the convenience of this feature would be worth (for minimum viable governance):
- Would we want a threshold to be lowered by abstaining CC? what if it becomes a threshold of 1? would that be okay?
- What should happen if all CC members abstain?
- How should a state of no confidence interact with this?

**Comment by Hornan7** [comment]
> * Would we want a threshold to be lowered by abstaining CC? what if it becomes a threshold of 1? would that be okay?

     - From my point of view I believe that 1 CC member would be a bad thing from an ideological point of view.
       Acceptable Threshold =
       Threshold > 1 (to avoid any state of dictatorship)
             &&
       Threshold = 0 to allow the CC Size mentionned at [line 1016 of CIP-1694](https://github.com/cardano-foundation/CIPs/blob/e28afa92478e8cc75934183f7f1d166e1c6dcaf8/CIP-1694/README.md?plain=1#L1016)

> * What should happen if all CC members abstain?
   - At this point this could eventually make the community ratify a motion of no confidence due to the absence of decision- 
     making by the committee and the view of several governance actions which reach their expiry without being considered by 
     the CC. 

> * How should a state of no confidence interact with this?
    -Same as for the other CC voting options, nothing is valid anymore until (2. New constitutional committee and/or threshold 
     and/or term limits) is ratified / then enacted. one epoch later.

These are just suggestions, but I think it makes sense.

**Comment by Hornan7** [comment]
Based on my current experience as a member of the ICC and the understanding that the committee may be composed primarily of consortiums and companies in the future, I have concluded that the need for this feature is no longer relevant. Therefore, I will be closing this issue.
