### ISSUE TITLE
CIP-30 Extension Naming

### ISSUE THREAD

**Issue by Ryun1** [cardano-foundation/CIPs#590]
Although we live in a world where CIP-30 is the default Cardano wallet-web connector, this may not always be the case, thus explicitly tying CIP-30 extensions to CIP-30 maybe a mistake.

I propose that we include these proposal titles something like "Web-Wallet Bridge", so something like #509 would be named "Governance Web-Wallet Bridge". I am bad at naming, so just wanted to create an issue to start the conversation.

Thoughts?
@rphair @KtorZ @Crypto2099

**Comment by rphair** [comment]
I seconded this motion at the CIP meeting this week ✅ but would also suggest that _Web-Wallet Bridge_ or equivalent **precede** the extension (e.g. _Web-Wallet Bridge: Governance_) so they all collate together when CIP names are sorted.

**Comment by Ryun1** [comment]
@rphair 

Youre always good at naming! - _Web-Wallet Bridge: xxxx_ sounds good to me 😎

**Comment by rphair** [comment]
@Ryun1 if nobody thinks these new names are out of place (so far the consensus looks in favour), perhaps we can declare this issue closed in meeting # 73 so I'll put it on the agenda.

**Comment by Ryun1** [comment]
@rphair I agree!

**Comment by Ryun1** [comment]
The only is that the colon (:) creates a YAML error when in the proposal header

`Error in user YAML: (<unknown>): mapping values are not allowed in this context at line 2 column 25`

@rphair

**Comment by rphair** [comment]
Aha.  Colon = mapping syntax.  Thanks; I've been trying to narrow that down for the longest time. 🥴

Typographically the best equivalent of a colon would be an em dash (—) but since we should stick to keyboard characters how about a minus sign?  @Ryun1 @Crypto2099 @Scitz0

> Web-Wallet Bridge - xxxx

**Comment by Ryun1** [comment]
In CIP editors call 73, we decided to move to use pipe ( | ) character. PR with information to follow.

**Comment by rphair** [comment]
Suggested update to CIP naming convention here (along with how we might update CIP-0030 in kind): https://github.com/cardano-foundation/CIPs/pull/594
