### ISSUE TITLE
CIP-9999 | How to add Copyright to CPSs

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/CIPs#759]
I have a PR half-created for this and ran into a stumbling block I hadn't considered in my https://github.com/cardano-foundation/CIPs/pull/756#issuecomment-1925794686 ... that if a Copyright section for CPSs were optional then we'd also have our first optional field in YAML headers since CIP-0001 was "reworked".

I don't think this is a problem syntactically, but it's all the more reason to first settle the recently proposed licensing question for CPSs according to which of these 3 options to take:

1. Do **nothing**: keep our current state of CPSs not having a Copyright section and generally covered by no open source licensing agreements.
1. Make CPS licensing **optional**: introducing it as an _optional section_ as recently added to CIP-9999... only requiring that it be the final section & sticking to 1 of the 2 licenses declared acceptable all along for CIPs (generally CC for documentation, Apache for code).
1. Make CPS licensing **mandatory**: simpler for syntax in both the CIP-9999 text and a universal YAML header field for every CPS.

Personally I don't see a universal need for mandatory open source licensing for CPSs unless the issues of warranty disclaimer and liability are considered.  Technically CIP editors as well as CPS authors and related CIP implementors would be included in liability scope unless someone can demonstrate otherwise.

What I don't know is what discussion preceded the current default of no licensing for CPSs: including why the CPS was excluded from the requirements imposed on the CIP.  This is my last specific request to @KtorZ and associates (@michaelpj?) & if no response then perhaps no particular investigation or discussion preceded this current question & we can consider all options anew.

Anyone with the means to present this to an appropriate legal authority, please do so.

Once we decide which of the 3 options above to take I have a PR half-written to cover it... though any particular suggestions of method & wording would be welcome here. 😎

**Comment by michaelpj** [comment]
This seems like an obvious oversight. I can't see any reason why CIPs and CPSs would differ in this regard.

**Comment by Ryun1** [comment]
> 3. Make CPS licensing mandatory: simpler for syntax in both the CIP-9999 text and a universal YAML header field for every CPS.

Lets just go for this.
I agree with Michael, this was probably just an oversight.

**Comment by rphair** [comment]
@michaelpj @Ryun1 that's great: the CPS headers, CPS template, and the CIP-9999 body (since it won't overburden the _optional sections_) will all be simpler & easier to follow as such.

Will file a PR soon to "fix" this issue & do the corresponding work to fix the merged CPSs and update the ones in progress.
