### ISSUE TITLE
CIP-100 | Canonical example is wrong

### ISSUE THREAD

**Issue by kderme** [cardano-foundation/CIPs#781]
The [canonical form](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/example.canonical) of the [example](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/example.json) is wrong, for example it misses the `hashAlgorithm` key

**Comment by Ryun1** [comment]
Good spot!

I will get a PR to fix this one shortly.

**Comment by Ryun1** [comment]
See #782

**Comment by Quantumplation** [comment]
It is not intended to include the `hashAlgorithm` key; see the comment I just left in #782

**Comment by kderme** [comment]
The example was fixed, thank you
