### ISSUE TITLE
hertsjeansofisceli@gmail.com celiaparr@jeansofialia.com Celia María dela Cruz parra PRPLCL75011631M700 //me adstengo no me gusta prestar mis nombre res x el riesgo  personal.....PAPC7501166A1///iDMEX1600329607//11163<5

### ISSUE THREAD

**Issue by Celiaparra** [cardano-foundation/CIPs#791]
< spam & malicious software links deleted >

**Comment by rphair** [comment]
Have edited above Spam comment & submitted an Abuse report for @Celiaparra to GitHub as follows:
> Repeated Spam violations (this is the sixth, and we've warned them before): https://github.com/cardano-foundation/CIPs/issues?q=is%3Aissue+author%3ACeliaparra
>
> We would suggest this person have their GitHub account itself closed.  Current maintainers don't have the correct permissions to ban this user from the repository (I'm not sure if this "block" request means the same thing).

**Comment by Celiaparra** [comment]
No joven mi registro es de desde mis 2añis de navidad y losiguiente los actualice en el 3011/2017/1/2019 que cosa tal vez algún ladrón te ISO creer lo contrario.....

**Comment by rphair** [comment]
@Celiaparra whether you are indeed malicious or just mentally ill, the result needs to be the same: we need you to stop posting to this repository.
